#!/bin/bash

# Cache SSH key if necessary
# Copyright (c) 2025 Manuel Schlund <schlunma@gmail.com>
# Licensed under the GNU General Public License v3.0 (or later).


# Get current status of ssh-add
ssh-add -l &>/dev/null
EXITCODE=$?

# Check if agent is running
if [ $EXITCODE -gt 1 ]; then
    >&2 echo "WARNING: SSH agent not running!"
    exit 1
fi

# Remove another specified key if desired (run script with arbitrary argument)
if [ $# -gt 0 ]; then
    for key in "$HOME/.ssh/id_rsa_REMOVE"; do
        ssh-add -d $key &>/dev/null
        if [ $? -eq 0 ]; then
            echo "SSH agent: Removed key $key for security reasons."
        fi
    done
fi

# Add desired SSH key if necessary
if [ $EXITCODE -gt 0 ]; then
    for key in "$HOME/.ssh/id_rsa_ADD_1" "$HOME/.ssh/id_rsa_ADD_2"; do
        ssh-add $key
    done
fi
